name: tabler_icons
description: Tabler Icons for flutter using icons from https://github.com/tabler/tabler-icons by Csaba Kissi @csaba_kissi

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: tabler-icons
      fonts:
        - asset: lib/fonts/tabler-icons.ttf
          style: normal
          weight: 400
