dependencies:
  flutter:
    sdk: flutter
description: Tabler Icons for flutter using icons from https://github.com/tabler/tabler-icons
  by Dashbrains. Original work by Csaba Kissi @csaba_kissi
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  fonts:
  - family: tabler-icons
    fonts:
    - asset: assets/fonts/tabler-icons.ttf
      style: normal
      weight: 400
homepage: https://github.com/DashBrains/tabler_icons_flutter
name: tabler_icons_flutter
repository: https://github.com/DashBrains/tabler_icons_flutter
version: 2.1.2
